
# Site Settings
title: Training by Serli
email: tanguy.desplebain@serli.com
description: Training by Serli . FORMATIONS & WORKSHOPS
url: "https://serli.github.io/"
github_username:  Serli
encoding: utf-8
# Build Settings
sass:
  sass_dir: _sass
include: ['js']
kramdown:
  input: GFM
